import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt-BR" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        {/* Cabeçalho */}
        <header className="header-titulo">
          <h1>Portal de Destinos Turísticos</h1>
        </header>

        {/* Menu de Navegação */}
        <nav className="menu-navegacao-barra">
          <Link href="/">Início</Link>
          <Link href="/destinos">Destinos</Link>
        </nav>

        {/* Conteúdo das páginas */}
        <main>{children}</main>

        {/* Rodapé */}
        <footer className="footer-direitos">
          © {new Date().getFullYear()} Portal de Destinos Turísticos. Todos os direitos reservados.
        </footer>
      </body>
    </html>
  );
}
